#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-scaler-pay-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka

#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000
server:
  port: 8082


redis:
 hostname: 127.0.0.1
 port: 6379


#xxl-sso:
#  excluded:
#    paths:
#xxl:
#  sso:
#    server: http://xxlssoserver.com:8080/xxl-sso-server
#    logout:
#      path: /logout
#    redis:
#      address: redis://127.0.0.1:6379


